### ISSUE TITLE
Add ship landing example

### ISSUE THREAD

**Issue by srmainwaring** [srmainwaring/asv_wave_sim#20]
This issue is to track adding a ship landing example using the WAM-V (scaled) and an Alti-Transition quad-plane from ArduPilot/SITL_Models. It is intended as a PoC / demo and is not intended to be merged back into the ignition-marine branch.

### Example branch

https://github.com/srmainwaring/asv_wave_sim/tree/feature/ship-landing-demo

### Tasks

- [x] Add scaled up version of the WAM-V model
- [x] Rescale wave model (larger dimension / lower local resolution)
- [x] Ensure Hydrodynamics water patch is sufficient
- [x] Enable scaling / steepness params to be adjusted for FFT
- [x] Update SITL params for WAM-V
- [x] Update joint PID controller params for WAM-V
- [x] Add example launch files for SITL and MAVProxy
- [x] Add user guide for building and running the example

**Comment by srmainwaring** [comment]
### User Guide

#### Dependencies


#### Build


#### Run
