### ISSUE TITLE
Add FFT wave generation using ECKV variance spectrum with cos-2S spreading function

### ISSUE THREAD

**Issue by srmainwaring** [srmainwaring/asv_wave_sim#22]
This issue is to track improvements to the FFT wave generation model.

### Issues with the current FFT wave model:

-  There are missing scale factors when discretising the continuous Pierson-Moskowitz (PM) variance spectrum which means the simulated spectrum is not correct (and does not behave at all well as the resolution N is altered).
- The PM spectrum is omni-directional and the method used to implement travelling time-dependent waves is not very natural (and possibly is not Hermitian in the frequency domain leading to an imaginary component in the wave field).
- It is not possible to set the wave direction from the parameters (or rather it is, but it has no effect).

### Proposed solution:

- Follow Curtis Mobley's detailed tutorial on generating sea surfaces from [Ocean Optics](https://www.oceanopticsbook.info/view/surfaces/level-2/modeling-sea-surfaces) taking care to include the correct scaling when transitioning from continuous one-sided spectra to discrete two-sided spectra
- Use the ECKV omni-directional spectra with the cos-2S spreading function to generate travelling time-dependent waves
- Allow the downwind direction to be specified as a parameter (using an angle from the positive x-axis (east in ENU coordinates))
- Add checks for various statistical properties of the waves and confirm the Fourier amplitudes are Hermitian.
  
### Tracking implementation on this branch:

- https://github.com/srmainwaring/asv_wave_sim/tree/feature/fft-eckv-cos2s

### Task list

- [x] Add new FFT wave simulation class
- [x] Integrate FFT class into OceanTile and enable in SDF models
- [x] Add ECKV omni-directional spectrum
- [x] Add ECKV and cosine-2S spreading functions
- [x] Port prototype from Python to C++
- [x] Check FFTW vs NumPy / SciPy FFT conventions
- [x] FFT for wave height
- [x] Enable parameters to control wind speed and direction  
- [x] FFT for wave height derivatives
- [x] FFT for horizontal displacements
- [x] FFT for horizontal displacements derivatives
- [x] Update SDF parameter options
- [x] First round of optimisation

**Comment by srmainwaring** [comment]
Waves for u10 = 7 m/s with downwind rotated clockwise 45 deg from the positive x-axis   

![ign-marine-v2](https://user-images.githubusercontent.com/24916364/166713912-3344f1be-dcfa-4620-842f-a04e32a3a714.jpg)

### Issues

Models appear to 'bounce' on the waves - could be:

- Wave speed is too high - check spreading function and dispersion
- Update rate of 30 Hz for wave physics is too slow - try increasing
- Water patch is too coarse - try refining and migrate the markers for the patch and water levels for debugging

**Comment by srmainwaring** [comment]
Closed by #23
