### ISSUE TITLE
Add GUI plugin to control wave environment

### ISSUE THREAD

**Issue by srmainwaring** [srmainwaring/asv_wave_sim#30]
The original version for Gazebo11 includes an executable that allows wave parameters to be updated dynamically without needed to reload the wave model. For Ignition Gazebo it is proposed to replace this with a GUI plugin that can be loaded into the sidebar and used to control the wave environment directly.

## Prototype

![WavesGUIPluginPrototype](https://user-images.githubusercontent.com/24916364/168490560-ab892d24-fc51-4b32-8cb3-c5c5c43a4c57.jpg)

## Tasks

- [ ] Add standalone GUI plugin for waves controls
- [ ] Integrate the GUI plugin into the project build
- [ ] Migrate original Gazebo11 param_v messages to Ignition equivalents
- [ ] Publish wave params messages from Waves Control GUI plugin
- [ ] Subscribe to wave params messages in Waves visual system
- [ ] Subscribe to wave params messages in Waves model system

Checkboxes for markers are provided in the prototype - defer implementing these to a followup issue.
